￼
￼
￼
Waterloo High School Students Proudly Present...
ADAM WAINWRIGHT and CRAIG CAMPBELL 
At Waterloo High School in the Auditorium on Saturday March 22, 2025 All proceeds benefiting Monroe County House of Neighborly Service


Afternoon Show
Evening Show

‐Doors open at 2:00
‐Doors open at 6:30
‐Show begins at 3:00
‐Show begins at 7:30
$50 per ticket - General Admission
CLICK HERE for Afternoon tickets
CLICK HERE for Evening tickets
A big thanks to all our sponsors!!!
￼     
￼    ￼    ￼    ￼    ￼
Created by Hannah.A, WHS Student
